### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kszqq** [BADBADBADBOY/pytorchOCR#1]
When I train, there is an error in the code：

Traceback (most recent call last):
  File "det_train.py", line 259, in <module>
    TrainValProgram(config)
  File "det_train.py", line 145, in TrainValProgram
    train_dataset = create_module(config['trainload']['function'])(config)
  File "/home/z/liao/pytorchOCR-master/ptocr/dataloader/DetLoad/PANProcess.py", line 23, in __init__
    img_list, label_list = self.get_base_information(config['trainload']['train_file'])
  File "/home/z/liao/pytorchOCR-master/ptocr/dataloader/DetLoad/PANProcess.py", line 63, in get_base_information
    result = self.get_bboxes(line[1])
IndexError: list index out of range

 What is the reason? Could the author please answer it?

**Comment by BADBADBADBOY** [comment]
https://github.com/BADBADBADBOY/pytorchOCR/blob/master/data/example/train_list.txt ，  Is your train_list.txt the same as this one, separated by \t in the middle

**Comment by kszqq** [comment]
thank you very much



---Original---

**Comment by BADBADBADBOY** [comment]
> When I train, there is an error in the code：
> 
> Traceback (most recent call last):
> File "det_train.py", line 259, in 
> TrainValProgram(config)
> File "det_train.py", line 145, in TrainValProgram
> train_dataset = create_module(config['trainload']['function'])(config)
> File "/home/z/liao/pytorchOCR-master/ptocr/dataloader/DetLoad/PANProcess.py", line 23, in **init**
> img_list, label_list = self.get_base_information(config['trainload']['train_file'])
> File "/home/z/liao/pytorchOCR-master/ptocr/dataloader/DetLoad/PANProcess.py", line 63, in get_base_information
> result = self.get_bboxes(line[1])
> IndexError: list index out of range
> 
> What is the reason? Could the author please answer it?

https://github.com/BADBADBADBOY/pytorchOCR/blob/master/data/example/train_list.txt ， Is your train_list.txt the same as this one, separated by \t in the middle

**Comment by BADBADBADBOY** [comment]
After that, I will update some more detailed training documents

**Comment by kszqq** [comment]
@BADBADBADBOY 
What is train_list.txt in your CRNN training? Can you give me an example?

**Comment by BADBADBADBOY** [comment]
example：img_path+label,    such as  /src/notebooks/train/1,jpg  hello

**Comment by kszqq** [comment]
thank you very much！

**Comment by kszqq** [comment]
@BADBADBADBOY 
When running rec_train.py, does the author have the following errors:
Training from scratch.

Traceback (most recent call last):
  File "rec_train.py", line 219, in <module>
    TrainValProgram(config)
  File "rec_train.py", line 186, in TrainValProgram
    loss_write = ModelTrain(train_data_loader,LabelConverter, model, criterion, optimizer, loss_bin, config, epoch)
  File "rec_train.py", line 51, in ModelTrain
    loss = criterion(pre_batch, gt_batch)
  File "/home/z/anaconda3/envs/chinese-ocr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/liao/pytorchOCR-master/ptocr/model/architectures/rec_model.py", line 42, in forward
    return self.loss(pre_batch, gt_batch)
  File "/home/z/anaconda3/envs/chinese-ocr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/liao/pytorchOCR-master/ptocr/model/loss/ctc_loss.py", line 12, in forward
    loss = self.criterion(preds, labels, preds_size, labels_len)
  File "/home/z/anaconda3/envs/chinese-ocr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/anaconda3/envs/chinese-ocr/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 1295, in forward
    self.zero_infinity)
  File "/home/z/anaconda3/envs/chinese-ocr/lib/python3.6/site-packages/torch/nn/functional.py", line 1767, in ctc_loss
    zero_infinity)

RuntimeError: Tensor for argument #2'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu)
